# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Live Bus Time' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Live Bus Time

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'RevealingSplashView'


  target 'Live Bus TimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Live Bus TimeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
